In [27]:
from neurotron import Terminal,Collab,Excite,Matrix,column,OR,AND
import neurotron.math.matrix as mx
import neurotron.math.matfun as mf


In [28]:
collab = Terminal(Collab(3,7,2,5))
collab.map()

K: +-000/0-+-003/3-+-006/6-+-009/9-+-012/C-+-015/F-+-018/I-+
   |  12   |  45   |  78   |  AB   |  DE   |  GH   |  JK   |
   +-001/1-+-004/4-+-007/7-+-010/A-+-013/D-+-016/G-+-019/J-+
   |  02   |  35   |  68   |  9B   |  CE   |  FH   |  IK   |
   +-002/2-+-005/5-+-008/8-+-011/B-+-014/E-+-017/H-+-020/K-+
   |  01   |  34   |  67   |  9A   |  CD   |  FG   |  IJ   |
   +-------+-------+-------+-------+-------+-------+-------+
P: +-000/0-+-003/3-+-006/6-+-009/9-+-012/C-+-015/F-+-018/I-+
   |  11   |  11   |  11   |  11   |  11   |  11   |  11   |
   +-001/1-+-004/4-+-007/7-+-010/A-+-013/D-+-016/G-+-019/J-+
   |  11   |  11   |  11   |  11   |  11   |  11   |  11   |
   +-002/2-+-005/5-+-008/8-+-011/B-+-014/E-+-017/H-+-020/K-+
   |  11   |  11   |  11   |  11   |  11   |  11   |  11   |
   +-------+-------+-------+-------+-------+-------+-------+
W: +-000/0-+-003/3-+-006/6-+-009/9-+-012/C-+-015/F-+-018/I-+
   |  11   |  11   |  11   |  11   |  11   |  11   |  11   |
   +-001/1-+-004/4-+-007

In [29]:
c = Matrix(1,3*7); c[0] = c[2*3] = c[6*3] = 1;print('c:',c.reshape(3,7))
collab(c)

c: [1 0 1 0 0 0 1; 0 0 0 0 0 0 0; 0 0 0 0 0 0 0]


[0 0 0 0 0 0 0; 1 0 1 0 0 0 1; 1 0 1 0 0 0 1]

In [30]:
collab.K.map('K: ');collab.empower(c).map('E: ')

K: +-000/0-+-003/3-+-006/6-+-009/9-+-012/C-+-015/F-+-018/I-+
   |  12   |  45   |  78   |  AB   |  DE   |  GH   |  JK   |
   +-001/1-+-004/4-+-007/7-+-010/A-+-013/D-+-016/G-+-019/J-+
   |  02   |  35   |  68   |  9B   |  CE   |  FH   |  IK   |
   +-002/2-+-005/5-+-008/8-+-011/B-+-014/E-+-017/H-+-020/K-+
   |  01   |  34   |  67   |  9A   |  CD   |  FG   |  IJ   |
   +-------+-------+-------+-------+-------+-------+-------+
E: +-000/0-+-003/3-+-006/6-+-009/9-+-012/C-+-015/F-+-018/I-+
   |  00   |  00   |  00   |  00   |  00   |  00   |  00   |
   +-001/1-+-004/4-+-007/7-+-010/A-+-013/D-+-016/G-+-019/J-+
   |  10   |  00   |  10   |  00   |  00   |  00   |  10   |
   +-002/2-+-005/5-+-008/8-+-011/B-+-014/E-+-017/H-+-020/K-+
   |  10   |  00   |  10   |  00   |  00   |  00   |  10   |
   +-------+-------+-------+-------+-------+-------+-------+


In [31]:
A=Matrix([[1,2,-1],[0,0,0]])
print('A:',A,'\nA:',A!=0)
A.N

A: [1 2 -1; 0 0 0] 
A: [1 1 1; 0 0 0]


[0 0 0; 1 1 1]

In [32]:
B=mf.MAGIC(3)[:2,:]<=3;B

[0 1 0; 1 0 0]

In [33]:
from numpy import array
A = Matrix([0,1,0]);  B = Matrix([1,1,0])
C=column(A,B); print('C:',C)
A,B,C


C: [0 1 0; 1 1 0]


([0 1 0], [1 1 0], [0 1 0; 1 1 0])

In [34]:
print(A)
OR(A,B),AND(A,B)

[0 1 0]


([1 1 0], [0 1 0])

In [35]:
CC=array(C);CC

array([[0., 1., 0.],
       [1., 1., 0.]])

In [36]:
B=Matrix([[1,1,1],[1,1,0]])!=0;B

[1 1 1; 1 1 0]

In [37]:
M=Matrix(1,3)
M[0,0]=all(B[:,0])
M[0,1]=all(B[:,1])
M[0,2]=all(B[:,2])
M

[1 1 0]